baseURL: https://example.com
title: Your title
theme: hugo-theme-m10c
paginate: 5
menu:
  main:
    - identifier: home
      name: Home
      url: /
    - identifier: tags
      name: Tags
      url: /tags/
params:
  author: John Doe
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula
    turpis sit amet elit pretium.
  menu_item_separator: ' - '
  social:
    - name: github
      url: https://github.com/gohugoio
    - name: twitter
      url: https://twitter.com/gohugoio
